name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install packages
        run: npm i
      
      - name: Build project
        run: npm run build

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: build
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
